Add gamepad support (#122)
marekmaskarinec/tophat pull request #171
Opened 2024-03-23 21:02 UTC by skejeton

This works only for Windows for now.

2024-03-29 02:13 UTC, skejeton commented
@marekmaskarinec requesting review...

2024-04-02 09:13 UTC, marekmaskarinec requested changes

2024-04-02 09:13 UTC, marekmaskarinec commented on umka/input.um
> +fn players*(): []Player {
I don't like the use of the name `Player`. Why not just use `Gamepad`?

2024-04-02 09:13 UTC, marekmaskarinec commented on umka/input.um
> +type GenericGamepadButton* = enum {
I think we can omit `Generic` here for the sake of brevity.

2024-04-02 16:54 UTC, marekmaskarinec approved these changes

2024-04-02 16:55 UTC, merged

2024-04-02 16:56 UTC, marekmaskarinec commented
@skejeton thank you for the work! I merged this into main, linux support is tbd. Please test if it works after the merge.

2024-04-02 20:01 UTC, skejeton commented
Ah Linux support was expected, I might work on it as well since I have the physical controller but it's a bit more involved. The merge works.